services:
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  postgres_test:
    image: postgres:15
    container_name: postgres_test
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: techstep_test
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data

  celery_worker:
    build: .
    container_name: celery_worker
    # MUDANÇA AQUI: Use -I para incluir as tarefas explicitamente
    command: celery -A app.worker.celery_app -I app.worker.tasks worker --loglevel=info 
    volumes:
      - .:/app
    depends_on:
      - redis

volumes:
  pgdata:
    driver: local
