version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A worker.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

volumes:
  pgdata:
    driver: local
