"""add status to interviews

Revision ID: 2edf9e0bdd4b
Revises: 100a226a2c29
Create Date: 2026-07-31 13:27:22.678831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2edf9e0bdd4b'
down_revision: Union[str, Sequence[str], None] = '100a226a2c29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('status', sa.String(length=30), server_default='applied', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'status')
    # ### end Alembic commands ###
