"""add ai credits

Revision ID: 9fb2fa056c12
Revises: b6314e1219e2
Create Date: 2026-08-24 11:42:41.832861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb2fa056c12'
down_revision: Union[str, Sequence[str], None] = 'b6314e1219e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_credit_balances',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('balance >= 0', name='ck_ai_credit_balances_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('ai_credit_purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('apple_transaction_id', sa.String(length=255), nullable=False),
    sa.Column('apple_original_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('credits_granted', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apple_transaction_id')
    )
    op.create_index(op.f('ix_ai_credit_purchases_apple_original_transaction_id'), 'ai_credit_purchases', ['apple_original_transaction_id'], unique=False)
    op.create_index(op.f('ix_ai_credit_purchases_user_id'), 'ai_credit_purchases', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_credit_purchases_user_id'), table_name='ai_credit_purchases')
    op.drop_index(op.f('ix_ai_credit_purchases_apple_original_transaction_id'), table_name='ai_credit_purchases')
    op.drop_table('ai_credit_purchases')
    op.drop_table('ai_credit_balances')
    # ### end Alembic commands ###
