"""Add skills to interviews

Revision ID: f4385331f232
Revises: 9eb3a8819a1d
Create Date: 2025-06-25 14:48:53.703537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4385331f232'
down_revision: Union[str, Sequence[str], None] = '9eb3a8819a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('job_seniority', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'job_seniority')
    # ### end Alembic commands ###
